Add var to allow bazel executable
Sometimes this is easier as long as you know it will be ok

diff --git a/bin/bazel b/bin/bazel
--- a/bin/bazel
+++ b/bin/bazel
@@ -1,7 +1,11 @@
 #!/bin/bash
 
-echo "called bad bazel" >&2
-exit 1
+set -euo pipefail
 
-# readonly script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
-# "$script_dir"/bz "$@"
+if [[ -z "${ALLOW_BAD_BAZEL:-}" ]]; then
+  echo "error: called bad bazel" >&2
+  exit 1
+fi
+
+script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
+exec "$script_dir"/bz "$@"
