[swift] Make build scripts work from nested dir

diff --git a/bin/build-swift b/bin/build-swift
--- a/bin/build-swift
+++ b/bin/build-swift
@@ -3,6 +3,16 @@
 set -euo pipefail
 set -x
 
+checkout_root="$PWD"
+while [[ ! -f "$checkout_root/swift/utils/build-script" ]]; do
+  if [[ "$checkout_root" == / ]]; then
+    echo "Could not find swift/utils/build-script in this directory or its ancestors" >&2
+    exit 1
+  fi
+  checkout_root="$(dirname "$checkout_root")"
+done
+cd "$checkout_root"
+
 args=(
   --reconfigure
   --release-debuginfo
diff --git a/bin/pull-swift-rel b/bin/pull-swift-rel
--- a/bin/pull-swift-rel
+++ b/bin/pull-swift-rel
@@ -3,4 +3,14 @@
 set -euo pipefail
 set -x
 
+checkout_root="$PWD"
+while [[ ! -f "$checkout_root/swift/utils/update-checkout" ]]; do
+  if [[ "$checkout_root" == / ]]; then
+    echo "Could not find swift/utils/update-checkout in this directory or its ancestors" >&2
+    exit 1
+  fi
+  checkout_root="$(dirname "$checkout_root")"
+done
+cd "$checkout_root"
+
 ./swift/utils/update-checkout --clone --scheme release/6.4.x
