[git] Reject args to cm
If I hit this with args it was likely a typo

diff --git a/bin/git-cm b/bin/git-cm
--- a/bin/git-cm
+++ b/bin/git-cm
@@ -7,6 +7,11 @@
 
 set -euo pipefail
 
+if [[ $# -gt 0 ]]; then
+  echo "error: unexpected args" >&2
+  exit 1
+fi
+
 config_key="$(git roothash).main-branch"
 if main_branch="$(git config --local "$config_key")"; then
   git checkout "$main_branch"
