Delete branch if pushes fail

diff --git a/bin/git-submitpr b/bin/git-submitpr
--- a/bin/git-submitpr
+++ b/bin/git-submitpr
@@ -48,6 +48,9 @@ if git -C "$worktree_dir" push --quiet --set-upstream origin "$branch_name"; the
   popd
 elif git -C "$worktree_dir" push --quiet --set-upstream mine "$branch_name"; then
   git -C "$worktree_dir" open --remote mine "pull/new/$branch_name"
+else
+  echo "error: failed to create remote branch" >&2
+  git branch -d "$branch_name"
 fi
 
 _checkout_empty
