Add --no-update to plugins script

diff --git a/bin/plugins b/bin/plugins
--- a/bin/plugins
+++ b/bin/plugins
@@ -22,6 +22,13 @@ containsElement() {
 
 names=()
 commands=()
+update=true
+if [[ "${1:-}" == --no-update ]]; then
+  update=false
+elif [[ -n "${1:-}" ]]; then
+  echo "error: invalid argument $1" >&2
+  exit 1
+fi
 
 while read -r repo
 do
@@ -33,7 +40,9 @@ do
   names+=("$name")
   path="$target/$name"
   if [[ -d "$path" ]];then
-    commands+=("echo '$path'; git -C '$path' pull")
+    if [[ "$update" == true ]]; then
+      commands+=("echo '$path'; git -C '$path' pull")
+    fi
   else
     commands+=("git clone --recursive https://github.com/$repo.git '$path'")
   fi
